# Generated by Django 2.0.13 on 2019-07-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigFire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive', models.BooleanField()),
                ('longitude', models.TextField()),
                ('latitude', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
