# Generated by Django 2.0.13 on 2019-07-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_auto_20190717_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive', models.BooleanField()),
                ('longitude', models.TextField()),
                ('latitude', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
